window.__TOPICS_LIST__ = [
  {"id": 1, "title": "挨拶（こんにちは）", "session": "こんにちは、何かお手伝いしましょうか", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 2, "title": "CSVにおけるテキストデータの型とダブルクォーテーションの意味", "session": "CSVにおけるテキストデータの扱い", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 3, "title": "セミコロンの使い方と自己紹介ページタイトルの書き方", "session": "セミコロンの使い方とページタイトル", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 4, "title": "MacのFinderサイドバーにゴミ箱を追加する方法", "session": "Finderサイドバーにゴミ箱を固定", "input_richness": "bare", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 5, "title": "CSSでitemContentsの幅を80%に変更", "session": "CSSでitemContentsの幅を変更", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 6, "title": "単機能モダンCSVエディタの紹介", "session": "単機能モダンCSVエディタの紹介", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 7, "title": "Slackボットの投稿通知設定", "session": "Slackボット投稿通知設定方法", "input_richness": "bare", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 8, "title": "日本の法人と個人の資産比較", "session": "法人と個人の資産比較", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 1},
  {"id": 9, "title": "Macのマウスホイールスクロール速度の調整", "session": "Macのマウススクロール速度調整", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 10, "title": "Statsigの発音方法", "session": "Statsigの発音方法", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 11, "title": "架空のユーザー顔写真の生成依頼", "session": "taustg user2 という名前の人物の顔写真", "input_richness": "bare", "expected_output": "artifact", "query_count": 3, "session_topic_count": 1},
  {"id": 12, "title": "GoogleドキュメントのNotion風目次表示", "session": "Googleドキュメントでの目次作成", "input_richness": "bare", "expected_output": "understanding", "query_count": 2, "session_topic_count": 2},
  {"id": 13, "title": "SmoothCSVのデータ転置機能の有無", "session": "Googleドキュメントでの目次作成", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 2},
  {"id": 14, "title": "CSV仕様書でのnullable表記法", "session": "CSVにおけるNull値のスマートな定義", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 15, "title": "FigmaのCtrl+ホイールズーム方向変更", "session": "Figma Ctrl+ホイールズーム方向変更", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 16, "title": "シンプルなテキストエディタの選び方", "session": "シンプルなテキストエディタの選び方", "input_richness": "bare", "expected_output": "understanding", "query_count": 2, "session_topic_count": 2},
  {"id": 17, "title": "Macでシェルスクリプトを実行する方法", "session": "シンプルなテキストエディタの選び方", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 2},
  {"id": 18, "title": "FFmpegによる動画→GIF変換シェルスクリプトの解説とデバッグ", "session": "シェルスクリプトによる高品質GIF変換", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 19, "title": "Macのフォーカスクリック動作の改善", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 11},
  {"id": 20, "title": "Finderの「よく使う項目」にフォルダを追加", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 11},
  {"id": 21, "title": "ChromeのPinP確認スキップ設定", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 11},
  {"id": 22, "title": "Mac起動時のアプリ自動操作", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 11},
  {"id": 23, "title": "crxMouseGestureの新しいタブ動作修正", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 11},
  {"id": 24, "title": "Homebrewのインストールとzsh環境設定", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "understanding", "query_count": 5, "session_topic_count": 11},
  {"id": 25, "title": "zshプロンプト表示のカスタマイズ", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 11},
  {"id": 26, "title": "GraphQLとProtobufの違い・GraphQLの詳細説明", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "understanding", "query_count": 3, "session_topic_count": 11},
  {"id": 27, "title": "ChromeでGeminiを便利に使う方法", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 11},
  {"id": 28, "title": "Chromeの縦タブ導入方法", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 11},
  {"id": 29, "title": "Mermaidのgraph LR記法と方向指定", "session": "Mac ウィンドウクリック操作の改善", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 11},
  {"id": 30, "title": "HRIS UIデザインアプローチ比較（OOUI/TOUI）", "session": "HRIS UIデザインアプローチ比較と結論", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 31, "title": "Krokiサーバーのステートレス設計とデータ永続性", "session": "Krokiサーバーのデータ永続性について", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 32, "title": "MacとLinuxのデフォルトPATHとパス追加方法", "session": "Macのデフォルトパスと追加方法", "input_richness": "bare", "expected_output": "understanding", "query_count": 4, "session_topic_count": 1},
  {"id": 33, "title": "YouTube再生速度2倍Chrome拡張機能の開発", "session": "YouTube 再生速度 2倍 Chrome 拡張", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 3, "session_topic_count": 1},
  {"id": 34, "title": "ダイアグラム作成ツールとDiagram as Codeの紹介", "session": "ダイアグラム作成ツールとDiagram as Code", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 35, "title": "データの直積フラット化の概念説明", "session": "データの直積をフラット化するとは", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 2},
  {"id": 36, "title": "CSV仕様のUI/CSVの一貫性に関するリライト", "session": "データの直積をフラット化するとは", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 2},
  {"id": 37, "title": "HRIS用ダミー従業員CSVデータ10件の生成", "session": "ダミー従業員データ生成", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 38, "title": "日本の銀行口座の一意特定に必要な情報", "session": "日本の銀行口座特定情報と取引の必要性", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 39, "title": "「むしろ」の言い換え表現", "session": "「むしろ」の言い換え表現", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 40, "title": "英文履歴書の職務経歴翻訳・リライト", "session": "Resume Work Experience Translation", "input_richness": "material", "expected_output": "artifact", "query_count": 10, "session_topic_count": 1},
  {"id": 41, "title": "Money Forwardの企業説明・呼称確認", "session": "Money Forward_ Fintech and SaaS Solutions", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 42, "title": "Googleスプレッドシートの高度な関数活用", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "material", "expected_output": "understanding", "query_count": 13, "session_topic_count": 20},
  {"id": 43, "title": "JSON/APIデータ構造の設計相談", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "material", "expected_output": "understanding", "query_count": 10, "session_topic_count": 20},
  {"id": 44, "title": "口座重複検出のフィールド命名相談", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "material", "expected_output": "understanding", "query_count": 6, "session_topic_count": 20},
  {"id": 45, "title": "登録済み口座の重複時UIメッセージ改善", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "material", "expected_output": "artifact", "query_count": 4, "session_topic_count": 20},
  {"id": 46, "title": "給与・賞与の総称（compensation等）", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 20},
  {"id": 47, "title": "Cursor AIのローカル動作確認", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 20},
  {"id": 48, "title": "OSごとのファイル名上限", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 20},
  {"id": 49, "title": "SO（ストックオプション）付与契約書テンプレート作成", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 5, "session_topic_count": 20},
  {"id": 50, "title": "スプレッドシートのJOIN関数で空白無視", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 20},
  {"id": 51, "title": "スプレッドシートで範囲の直積をフラット化", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "fact", "query_count": 3, "session_topic_count": 20},
  {"id": 52, "title": "R1C1記法の説明と別シート参照", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 20},
  {"id": 53, "title": "バリデーションの種類（構文/セマンティック）", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 20},
  {"id": 54, "title": "チェックボックスの不確定状態（indeterminate）", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 2, "session_topic_count": 20},
  {"id": 55, "title": "CSVエクスポート機能のチェックボックスラベル提案", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 1, "session_topic_count": 20},
  {"id": 56, "title": "英文法の確認（share meの誤り）", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "material", "expected_output": "fact", "query_count": 1, "session_topic_count": 20},
  {"id": 57, "title": "命名規則（キャメルケース/スネークケース）の慣習", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 20},
  {"id": 58, "title": "Macターミナルのプロンプト表示問題", "session": "Mac ターミナル プロンプト表示問題", "input_richness": "material", "expected_output": "understanding", "query_count": 4, "session_topic_count": 4},
  {"id": 59, "title": "Node.js実行ファイルのパス確認", "session": "Mac ターミナル プロンプト表示問題", "input_richness": "material", "expected_output": "fact", "query_count": 1, "session_topic_count": 4},
  {"id": 60, "title": "Chrome拡張機能開発の基本", "session": "Chrome拡張機能開発の第一歩", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 2, "session_topic_count": 1},
  {"id": 61, "title": "HTMLラジオボタンの正誤確認と修正", "session": "HTMLラジオボタンの修正と解説", "input_richness": "material", "expected_output": "understanding", "query_count": 4, "session_topic_count": 27},
  {"id": 62, "title": "DB正規化・非正規化・平坦化の用語確認", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 27},
  {"id": 63, "title": "CSV名称の命名相談（口座情報専用CSV）", "session": "HTMLラジオボタンの修正と解説", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 27},
  {"id": 64, "title": "マスターDBと履歴DBの設計相談", "session": "HTMLラジオボタンの修正と解説", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 5, "session_topic_count": 27},
  {"id": 65, "title": "グラフCSVの列名検討とツリー構造用語", "session": "HTMLラジオボタンの修正と解説", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 27},
  {"id": 66, "title": "3つの数値の一意性チェック方法", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 27},
  {"id": 67, "title": "CSV書き出し時の関数従属カラム含有是非", "session": "HTMLラジオボタンの修正と解説", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 27},
  {"id": 68, "title": "CSVインポート列の必須/任意/無視の変数名", "session": "HTMLラジオボタンの修正と解説", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 27},
  {"id": 69, "title": "MacでpythonコマンドをPython3にする方法", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 27},
  {"id": 70, "title": "「申請」の英訳とapplicationの混同回避", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 27},
  {"id": 71, "title": "PlantUMLでDB ER図作成", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "understanding", "query_count": 5, "session_topic_count": 27},
  {"id": 72, "title": "マルチテナントSaaS DB設計とパフォーマンス", "session": "HTMLラジオボタンの修正と解説", "input_richness": "material", "expected_output": "artifact", "query_count": 4, "session_topic_count": 27},
  {"id": 73, "title": "規定・規則の類語と「要領」の英訳", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 27},
  {"id": 74, "title": "AnyFlowの事業内容確認", "session": "HTMLラジオボタンの修正と解説", "input_richness": "material", "expected_output": "fact", "query_count": 1, "session_topic_count": 27},
  {"id": 75, "title": "CSVにおける数字文字列のベストプラクティス", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "understanding", "query_count": 3, "session_topic_count": 27},
  {"id": 76, "title": "消滅会社の法人番号の扱い", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 27},
  {"id": 77, "title": "ラムダ式の意味の解説", "session": "HTMLラジオボタンの修正と解説", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 27},
  {"id": 78, "title": "顔写真生成（tauprod）", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "artifact", "query_count": 1, "session_topic_count": 27},
  {"id": 79, "title": "クロス集計表・Pivot Viewの用語確認", "session": "HTMLラジオボタンの修正と解説", "input_richness": "contextualized", "expected_output": "fact", "query_count": 2, "session_topic_count": 27},
  {"id": 80, "title": "Android仕事用プロファイル問題", "session": "HTMLラジオボタンの修正と解説", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 27},
  {"id": 81, "title": "FroalaエディタとAsciiDocの中間表現調査", "session": "HTMLラジオボタンの修正と解説", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 3, "session_topic_count": 27},
  {"id": 82, "title": "顔写真生成（taustg user2）と背景色修正", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "artifact", "query_count": 3, "session_topic_count": 27},
  {"id": 83, "title": "Node.jsパス確認とインストール方法", "session": "HTMLラジオボタンの修正と解説", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 27},
  {"id": 84, "title": "allocationの略記とmallocの意味", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 27},
  {"id": 85, "title": "オートコンプリートUIの名称確認", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 27},
  {"id": 86, "title": "HRISを含む英単語の探索", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "artifact", "query_count": 1, "session_topic_count": 27},
  {"id": 87, "title": "ゆっくり発音の表記方法（英語）", "session": "HTMLラジオボタンの修正と解説", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 27},
  {"id": 88, "title": "Google Docs内画像のダウンロード方法", "session": "Google Docs 画像ダウンロード方法", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 2},
  {"id": 89, "title": "英語の趣味リスト表現の添削", "session": "Google Docs 画像ダウンロード方法", "input_richness": "material", "expected_output": "understanding", "query_count": 1, "session_topic_count": 2},
  {"id": 90, "title": "Firefox PWAがアプリドロワーに入らない問題", "session": "Firefox PWA アプリドロワー非対応", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 91, "title": "日本の人事労務システム機能比較調査", "session": "日本の人事労務システム機能比較", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 2, "session_topic_count": 1},
  {"id": 92, "title": "HTML/CSS/JSファイル分離とSticky列実装", "session": "HTML to Separate Files", "input_richness": "material", "expected_output": "artifact", "query_count": 3, "session_topic_count": 2},
  {"id": 93, "title": "Web機能追加時の英語表現（Affected screens等）", "session": "HTML to Separate Files", "input_richness": "contextualized", "expected_output": "fact", "query_count": 2, "session_topic_count": 2},
  {"id": 94, "title": "bi-temporalデータのtransaction_toとdeleted_atの違い", "session": "`transaction_to`と`deleted_at`の違い", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 2},
  {"id": 95, "title": "就業状態の変数名と公的給付金の英訳", "session": "`transaction_to`と`deleted_at`の違い", "input_richness": "contextualized", "expected_output": "fact", "query_count": 2, "session_topic_count": 2},
  {"id": 96, "title": "オンボーディングアンケートの目標・達成・課題まとめ", "session": "目標達成点課題点の情報提供依頼", "input_richness": "material", "expected_output": "artifact", "query_count": 2, "session_topic_count": 1},
  {"id": 97, "title": "ソフトウェア開発における期間変更の名称", "session": "ソフトウェア開発における期間変更の名称", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 2},
  {"id": 98, "title": "ポップアップからポップアップのBad Practice", "session": "ソフトウェア開発における期間変更の名称", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 2},
  {"id": 99, "title": "日本の銀行口座特定に必要な情報（全銀システム）", "session": "日本の銀行口座特定に必要な情報", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 4, "session_topic_count": 6},
  {"id": 100, "title": "SVGインラインHTML作成とChrome翻訳対応", "session": "日本の銀行口座特定に必要な情報", "input_richness": "material", "expected_output": "artifact", "query_count": 2, "session_topic_count": 6},
  {"id": 101, "title": "git cloneとcheckoutの違い", "session": "日本の銀行口座特定に必要な情報", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 6},
  {"id": 102, "title": "支給情報振り分けの図をHTML/CSSで構成", "session": "日本の銀行口座特定に必要な情報", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 6},
  {"id": 103, "title": "Twemoji一括ダウンロードと分類スクリプト", "session": "日本の銀行口座特定に必要な情報", "input_richness": "material", "expected_output": "artifact", "query_count": 8, "session_topic_count": 6},
  {"id": 104, "title": "Podman Desktopでpodmanコマンドが見つからない問題", "session": "日本の銀行口座特定に必要な情報", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 1, "session_topic_count": 6},
  {"id": 105, "title": "Google Sheets関数（範囲出力・パイプ処理）", "session": "Google Sheets 範囲出力関数一覧", "input_richness": "bare", "expected_output": "understanding", "query_count": 6, "session_topic_count": 2},
  {"id": 106, "title": "ツールバーメニューの「...」の意味", "session": "Google Sheets 範囲出力関数一覧", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 2},
  {"id": 107, "title": "Qiitaログインポップアップ非表示CSS", "session": "Qiita ログインポップアップ非表示 CSS", "input_richness": "material", "expected_output": "artifact", "query_count": 3, "session_topic_count": 1},
  {"id": 108, "title": "人事管理の口座・支給情報登録機能設計（OOUI/TOUI）", "session": "人事管理における口座・支給情報登録機能設計", "input_richness": "material", "expected_output": "understanding", "query_count": 3, "session_topic_count": 1},
  {"id": 109, "title": "CSSで矢印を上付き文字風に表示", "session": "CSSで矢印を上付き文字風に", "input_richness": "material", "expected_output": "artifact", "query_count": 3, "session_topic_count": 1},
  {"id": 110, "title": "数値選択UI（スピンボックス）の名称", "session": "数値選択UIの名称について", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 111, "title": "肖像写真生成失敗（Taustg User3）", "session": "肖像写真が見つかりません", "input_richness": "bare", "expected_output": "artifact", "query_count": 3, "session_topic_count": 1},
  {"id": 112, "title": "肖像写真生成とSQLインジェクション・XSS解説", "session": "肖像写真作成の可否と詳細", "input_richness": "bare", "expected_output": "artifact", "query_count": 4, "session_topic_count": 1},
  {"id": 113, "title": "C++/Haskell/Rustで書かれた普及プログラム", "session": "C++で書かれた普及プログラム", "input_richness": "bare", "expected_output": "fact", "query_count": 3, "session_topic_count": 1},
  {"id": 114, "title": "JiraとGoogle連携のアプリブロック解決", "session": "Jira Google連携「アプリブロック」の解決", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 115, "title": "Extraordinary All-handsのニュアンス", "session": "Extraordinary All-hands のニュアンス", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 5},
  {"id": 116, "title": "Sticky要素の✕ボタン非表示UIの議論", "session": "Extraordinary All-hands のニュアンス", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 5},
  {"id": 117, "title": "意味バリデーションと構文バリデーション", "session": "Extraordinary All-hands のニュアンス", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 5},
  {"id": 118, "title": "読みの長い日本人氏名の調査", "session": "Extraordinary All-hands のニュアンス", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 5},
  {"id": 119, "title": "ドルサインの位置と数値前置記号の調査", "session": "Extraordinary All-hands のニュアンス", "input_richness": "bare", "expected_output": "fact", "query_count": 3, "session_topic_count": 5},
  {"id": 120, "title": "Notion階層構造可視化Stylus CSS", "session": "Notion 階層構造可視化 Stylus CSS", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 3, "session_topic_count": 1},
  {"id": 121, "title": "SlackからNotionへのタスク作成連携", "session": "SlackからNotionへのタスク作成", "input_richness": "contextualized", "expected_output": "fact", "query_count": 2, "session_topic_count": 1},
  {"id": 122, "title": "マイナンバーサンプル番号の生成と検証", "session": "マイナンバーサンプル番号の生成", "input_richness": "bare", "expected_output": "artifact", "query_count": 3, "session_topic_count": 2},
  {"id": 123, "title": "被保険者番号・基礎年金番号の桁数", "session": "マイナンバーサンプル番号の生成", "input_richness": "contextualized", "expected_output": "fact", "query_count": 2, "session_topic_count": 2},
  {"id": 124, "title": "社会保険の短時間就労者の定義", "session": "社会保険の短時間就労者とは", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 3},
  {"id": 125, "title": "社会保険における職種の一覧の有無", "session": "社会保険の短時間就労者とは", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 3},
  {"id": 126, "title": "RDBMSのCHECK制約（カラム間制約）", "session": "社会保険の短時間就労者とは", "input_richness": "bare", "expected_output": "understanding", "query_count": 2, "session_topic_count": 3},
  {"id": 127, "title": "API連携のリダイレクトURIの仕組み", "session": "API連携におけるリダイレクトURIとは", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 128, "title": "英文ビジネス文書のリライト（保険料関連）", "session": "Rewriting Redundant Maintenance Effort", "input_richness": "material", "expected_output": "artifact", "query_count": 3, "session_topic_count": 1},
  {"id": 129, "title": "Mermaidユースケース図の作成", "session": "Mermaid ユースケース図作成", "input_richness": "material", "expected_output": "artifact", "query_count": 5, "session_topic_count": 1},
  {"id": 130, "title": "社会保険料がマイナスになるケース", "session": "社会保険料がマイナスになるケース", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 131, "title": "社会保険における「区分」（年金種別・等級・取得区分）", "session": "社会保険における「区分」とは？", "input_richness": "bare", "expected_output": "understanding", "query_count": 4, "session_topic_count": 3},
  {"id": 132, "title": "架空の苗字「たうすて」の漢字候補（区分セッション内）", "session": "社会保険における「区分」とは？", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 1, "session_topic_count": 3},
  {"id": 133, "title": "社保の英語公式ドキュメントの用語確認", "session": "社会保険における「区分」とは？", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 3},
  {"id": 134, "title": "PlantUML状態遷移図の横向き化", "session": "PlantUML 状態遷移図の横向き化", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 135, "title": "アイデミーの事業内容解説", "session": "アイデミーの事業内容を解説", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 2},
  {"id": 136, "title": "マネーフォワードのソフトウェア群の呼称", "session": "アイデミーの事業内容を解説", "input_richness": "contextualized", "expected_output": "fact", "query_count": 2, "session_topic_count": 2},
  {"id": 137, "title": ".NETの名前の由来と背景", "session": ".NETの名前の由来と背景", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 138, "title": "MapとReduceの並列計算の仕組み", "session": "Map と Reduce の並列計算", "input_richness": "bare", "expected_output": "understanding", "query_count": 1, "session_topic_count": 1},
  {"id": 139, "title": "TauToDo用Slack Reacjiデザイン提案", "session": "TauToDo Slack Reacji デザイン提案", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 3, "session_topic_count": 1},
  {"id": 140, "title": "社会保険料の自動計算外ケースと手入力理由", "session": "社会保険料計算の例外", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 141, "title": "TypeScript Enum定義（社保の性別・坑内員区分）", "session": "TypeScript Enum 定義の提案", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 142, "title": "架空の苗字「たうすて」の漢字候補", "session": "架空の苗字「たうすて」の漢字候補", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 143, "title": "資格取得届と算定基礎届の対応関係", "session": "資格取得届と算定基礎届の対応", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 144, "title": "各種社会保険料の上限額", "session": "社会保険料の上限額について", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 145, "title": "AIプロンプト作成支援とタスク整理", "session": "プロンプト作成支援：AI向け指示の具体化", "input_richness": "material", "expected_output": "artifact", "query_count": 13, "session_topic_count": 1},
  {"id": 146, "title": "会計ソフトOSSとマネージドサービスのビジネスモデル", "session": "会計ソフトOSSとマネージドサービス", "input_richness": "bare", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 147, "title": "クリップボードの実装の仕組み", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "understanding", "query_count": 1, "session_topic_count": 18},
  {"id": 148, "title": "Zigで実装されたソフトウェアの例", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 18},
  {"id": 149, "title": "英語の冠詞 the の使い分け", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 18},
  {"id": 150, "title": "yarn install時のGITHUB_TOKENエラーとGitHub認証", "session": "クリップボードの実装と仕組み", "input_richness": "material", "expected_output": "understanding", "query_count": 8, "session_topic_count": 18},
  {"id": 151, "title": "RDBMSのJSON型の仕組みとNoSQL比較", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "understanding", "query_count": 2, "session_topic_count": 18},
  {"id": 152, "title": "マイナンバーの利用目的の一覧調査", "session": "クリップボードの実装と仕組み", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 7, "session_topic_count": 18},
  {"id": 153, "title": "Git Blameでの直コミット判別", "session": "クリップボードの実装と仕組み", "input_richness": "material", "expected_output": "fact", "query_count": 2, "session_topic_count": 18},
  {"id": 154, "title": "条文の漢数字を算用数字に変換", "session": "クリップボードの実装と仕組み", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 18},
  {"id": 155, "title": "条文における又はと若しくはの違い", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 18},
  {"id": 156, "title": "番号法第9条の読みやすい箇条書き化", "session": "クリップボードの実装と仕組み", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 18},
  {"id": 157, "title": "Non-Japaneseメンバーという表現の適切さ", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 18},
  {"id": 158, "title": "grepの語源と意味", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 18},
  {"id": 159, "title": "Railsスキーマを表形式に整理", "session": "クリップボードの実装と仕組み", "input_richness": "material", "expected_output": "artifact", "query_count": 2, "session_topic_count": 18},
  {"id": 160, "title": "マイクロサービス間のマスターデータ同期手法", "session": "クリップボードの実装と仕組み", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 4, "session_topic_count": 18},
  {"id": 161, "title": "dependent: :nullifyとdependent: :destroyの違い", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 18},
  {"id": 162, "title": "UPSERT+DELETEによる完全同期の意味", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 18},
  {"id": 163, "title": "best-in-classの意味", "session": "クリップボードの実装と仕組み", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 18},
  {"id": 164, "title": "DB月単位データ型・給与計算ソフトの社保機能比較", "session": "クリップボードの実装と仕組み", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 5, "session_topic_count": 18},
  {"id": 165, "title": "全角括弧のマッチング正規表現・法令用語・漢数字変換", "session": "全角括弧のマッチング正規表現", "input_richness": "material", "expected_output": "artifact", "query_count": 3, "session_topic_count": 1},
  {"id": 166, "title": "都道府県コード順のリスト分析とWebサイト変更監視", "session": "都道府県コード順のリスト分析", "input_richness": "material", "expected_output": "fact", "query_count": 4, "session_topic_count": 1},
  {"id": 167, "title": "OpenAPI仕様書のビューワ作成", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 10},
  {"id": 168, "title": "IFTTTとZapierの対応SaaS数比較", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 10},
  {"id": 169, "title": "マネーフォワードAdminaはIDaaSか", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 10},
  {"id": 170, "title": "古典文法「歩かれむ」と万葉仮名・漢文表記", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "bare", "expected_output": "understanding", "query_count": 7, "session_topic_count": 10},
  {"id": 171, "title": "DITAの概要", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 10},
  {"id": 172, "title": "口座編集・削除時の影響を1文でまとめる", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 1, "session_topic_count": 10},
  {"id": 173, "title": "保険料額表の列追加可能性と坑内員等級統合の歴史", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 10},
  {"id": 174, "title": "標準報酬月額マスターと保険料テーブルのDB設計", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "material", "expected_output": "understanding", "query_count": 1, "session_topic_count": 10},
  {"id": 175, "title": "カスタム項目の無効化機能のユースケース", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 1, "session_topic_count": 10},
  {"id": 176, "title": "even の自然な位置（英語文法）", "session": "OpenAPIドキュメントビューワ作成", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 10},
  {"id": 177, "title": "Mermaid矢印に補足テキスト追加方法", "session": "Mermaid 矢印に補足テキストを追加", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 178, "title": "FFmpeg WAV to MP3変換コマンド", "session": "FFmpeg WAV to MP3 Conversion", "input_richness": "bare", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 179, "title": "債務超過時の分社化のリスクと実務", "session": "債務超過時の分社化：リスクと実務", "input_richness": "bare", "expected_output": "understanding", "query_count": 2, "session_topic_count": 11},
  {"id": 180, "title": "DBのConstraint（制約）の解説", "session": "債務超過時の分社化：リスクと実務", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 11},
  {"id": 181, "title": "社会保険料の端数処理ルール", "session": "債務超過時の分社化：リスクと実務", "input_richness": "contextualized", "expected_output": "fact", "query_count": 4, "session_topic_count": 11},
  {"id": 182, "title": "健保と厚年の等級不一致ケースの網羅的検討", "session": "債務超過時の分社化：リスクと実務", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 7, "session_topic_count": 11},
  {"id": 183, "title": "バリデーション仕様書の英語用語", "session": "債務超過時の分社化：リスクと実務", "input_richness": "material", "expected_output": "fact", "query_count": 2, "session_topic_count": 11},
  {"id": 184, "title": "エラーコードの英語表現", "session": "債務超過時の分社化：リスクと実務", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 11},
  {"id": 185, "title": "HTTPメソッドCREATEとAPI設計", "session": "債務超過時の分社化：リスクと実務", "input_richness": "material", "expected_output": "understanding", "query_count": 5, "session_topic_count": 11},
  {"id": 186, "title": "国保組合加入者の厚年随時改定判定", "session": "債務超過時の分社化：リスクと実務", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 1, "session_topic_count": 11},
  {"id": 187, "title": "情報セキュリティの3要素（CIA）と7要素", "session": "債務超過時の分社化：リスクと実務", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 11},
  {"id": 188, "title": "銀行口座のカナと漢字の使い分け", "session": "債務超過時の分社化：リスクと実務", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 1, "session_topic_count": 11},
  {"id": 189, "title": "健保等級でnull: falseの場合の国保組合対応", "session": "債務超過時の分社化：リスクと実務", "input_richness": "material", "expected_output": "fact", "query_count": 1, "session_topic_count": 11},
  {"id": 190, "title": "マスターデータの対義語（トランザクション/コンシューマ）", "session": "マスターの対義語：トランザクションとコンシューマ", "input_richness": "bare", "expected_output": "fact", "query_count": 4, "session_topic_count": 1},
  {"id": 191, "title": "Google Docs画像コピーChrome拡張の開発", "session": "Google Docs 画像コピーChrome拡張", "input_richness": "material", "expected_output": "artifact", "query_count": 11, "session_topic_count": 2},
  {"id": 192, "title": "PRD要件書の英訳", "session": "Google Docs 画像コピーChrome拡張", "input_richness": "material", "expected_output": "understanding", "query_count": 5, "session_topic_count": 2},
  {"id": 193, "title": "HR Tech SaaSスローガンの解釈と英語表現", "session": "HR Tech SaaS_ Paper Pusher to People Partner", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 6},
  {"id": 194, "title": "写真の色補正（オレンジ色被り除去）", "session": "HR Tech SaaS_ Paper Pusher to People Partner", "input_richness": "material", "expected_output": "artifact", "query_count": 4, "session_topic_count": 6},
  {"id": 195, "title": "Teach meの不自然さと適切な英語表現", "session": "HR Tech SaaS_ Paper Pusher to People Partner", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 6},
  {"id": 196, "title": "白黒写真のカラー化", "session": "HR Tech SaaS_ Paper Pusher to People Partner", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 6},
  {"id": 197, "title": "SaaS is deadの出典と文脈解説", "session": "HR Tech SaaS_ Paper Pusher to People Partner", "input_richness": "bare", "expected_output": "understanding", "query_count": 1, "session_topic_count": 6},
  {"id": 198, "title": "白黒写真をカラーに直す（別セッション）", "session": "この白黒写真をカラーに直して。白くて明るい部屋で取られた写真で、発言者の服の色は黒です", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 199, "title": "Googleドキュメントのプルダウン選択肢上限とMySQL型調査", "session": "Googleドキュメントのプルダウン選択肢上限", "input_richness": "bare", "expected_output": "fact", "query_count": 9, "session_topic_count": 4},
  {"id": 200, "title": "CursorでGitブランチ名を表示・git push問題解決", "session": "CursorでGitブランチ名を表示する方法", "input_richness": "bare", "expected_output": "understanding", "query_count": 5, "session_topic_count": 1},
  {"id": 201, "title": "SaaS is dead 2030年PdM像のブログ共同執筆", "session": "SaaSの終焉とAIの台頭", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 17, "session_topic_count": 1},
  {"id": 202, "title": "プレモーテムMECEフレームワーク・社保の被保険者区分", "session": "プレモーテムMECEフレームワーク集", "input_richness": "bare", "expected_output": "understanding", "query_count": 8, "session_topic_count": 1},
  {"id": 203, "title": "ダミー従業員の顔写真生成とUIアイコン調査", "session": "従業員_従業員番号_L002_氏名_倒捨 ろぐに_氏名（フリガナ）_タウステ ログニ_所属_主務かどうか_主務_組織_社長_事業部_営業部_役職_役職1_ID_マネーフォワード ID_taustg-login2_ログイ.md", "input_richness": "material", "expected_output": "artifact", "query_count": 2, "session_topic_count": 1},
  {"id": 204, "title": "NotionでのHTMLホスティングと代替手段", "session": "NotionでのHTMLホスティングの可否", "input_richness": "bare", "expected_output": "fact", "query_count": 5, "session_topic_count": 1},
  {"id": 205, "title": "厚年非加入・健保加入の可能性とシステム設計", "session": "厚年非加入・健保加入の可能性", "input_richness": "contextualized", "expected_output": "fact", "query_count": 2, "session_topic_count": 1},
  {"id": 206, "title": "SaaS画面のHTML生成（フィルター+テーブルUI）", "session": "HTML を生成して。条件は以下___ 大きく分けて、上部と下部に分かれる。大きさは均等ではない (上部のほうが小さい)__ 上部はフィルター条件を指定する部分。___ 上部左端にはド.md", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 207, "title": "GitHubプライベートリポジトリ共有とREADME作成", "session": "GitHub プライベートリポジトリ共有方法", "input_richness": "bare", "expected_output": "understanding", "query_count": 12, "session_topic_count": 1},
  {"id": 208, "title": "健保と厚年で等級がずれる理由と届出様式", "session": "健保と厚年で等級がずれる理由", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 209, "title": "差し戻し申請の適用開始日バグのJira Epic作成", "session": "差し戻し申請の適用開始日バグ修正", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 210, "title": "FFmpegで動画をMP4に変換するコマンド", "session": "FFmpegで動画をMP4に変換", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 211, "title": "GitHubリポジトリREADMEの英訳", "session": "# Tau's Playground - PdM Sandbox and Idea Scraps__## 💡 概要_このリポジトリは、PdM 業務における__技術的な検証、UI モックアップ、一時的なスクリプト、アイデアの断片__を雑多に保管する.md", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 212, "title": "国保組合の保険料と等級・標準報酬月額の有無", "session": "国保組合の保険料と等級", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 1},
  {"id": 213, "title": "健康保険と国民健康保険の違い・公的医療保険の包括概念", "session": "健康保険と国民健康保険の違い", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 214, "title": "Miroの表の行を一括削除する方法", "session": "Miroの表の行を一括削除する方法", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 215, "title": "Miroのフレーム機能の説明とトラブルシュート", "session": "Miroフレーム機能の役割と使い方", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 1},
  {"id": 216, "title": "Notionで削除した記事を復元する方法", "session": "Notionで削除した記事を復元する方法", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 217, "title": "3Dセキュアのセキュリティ評価", "session": "3Dセキュアの現状と将来性", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 1, "session_topic_count": 2},
  {"id": 218, "title": "モンドリアンの絵画に関する調査", "session": "3Dセキュアの現状と将来性", "input_richness": "bare", "expected_output": "fact", "query_count": 4, "session_topic_count": 2},
  {"id": 219, "title": "Zoom録画コントロールバー常時表示Chrome拡張開発", "session": "Zoom録画再生時のコントロールバー常時表示", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 220, "title": "Bi-temporalデータ構造のブログ記事共同執筆", "session": "Bi-temporal データ構造のブログ記事作成", "input_richness": "material", "expected_output": "artifact", "query_count": 4, "session_topic_count": 5},
  {"id": 221, "title": "社会保険料計算の事業所・一括適用・保険料率", "session": "Bi-temporal データ構造のブログ記事作成", "input_richness": "bare", "expected_output": "artifact", "query_count": 5, "session_topic_count": 5},
  {"id": 222, "title": "Bi-temporalデータ構造のサンプルデータ作成", "session": "Bi-temporal データ構造のブログ記事作成", "input_richness": "bare", "expected_output": "artifact", "query_count": 1, "session_topic_count": 5},
  {"id": 223, "title": "国保組合加入者の雇用契約と適用除外制度", "session": "Bi-temporal データ構造のブログ記事作成", "input_richness": "bare", "expected_output": "understanding", "query_count": 3, "session_topic_count": 5},
  {"id": 224, "title": "プロフィール画像生成依頼", "session": "Bi-temporal データ構造のブログ記事作成", "input_richness": "bare", "expected_output": "artifact", "query_count": 1, "session_topic_count": 5},
  {"id": 225, "title": "ブラウザ拡張のパスキー保存構成の検討", "session": "ブラウザ拡張のパスキー保存構成", "input_richness": "bare", "expected_output": "understanding", "query_count": 1, "session_topic_count": 4},
  {"id": 226, "title": "e.g.の意味と由来", "session": "ブラウザ拡張のパスキー保存構成", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 4},
  {"id": 227, "title": "Google Docsプレゼンテーションのウィンドウ内開始", "session": "ブラウザ拡張のパスキー保存構成", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 4},
  {"id": 228, "title": "システム仕様の整理（エンティティの対称性）", "session": "ブラウザ拡張のパスキー保存構成", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 4},
  {"id": 229, "title": "JSON配列とオブジェクトの順序保証", "session": "JSON配列とオブジェクトの順序保証", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 230, "title": "半期目標設定のリライト提案", "session": "半期目標設定のリライト提案", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 231, "title": "HTMLテーブル改造・データ追記スクリプト", "session": "HTMLテーブル改造・データ追記スクリプト", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 232, "title": "Notionで写真アルバムを作成する方法", "session": "Notionで写真アルバムを作成する方法", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 233, "title": "PulumiとOpenTofuの違い", "session": "PulumiとOpenTofuの違い", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 234, "title": "社会保険料等級表のOCR", "session": "OCR結果：社会保険料等級表", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 235, "title": "JSON型定義のベストプラクティス（TypeScript）", "session": "JSON 型定義のベストプラクティス", "input_richness": "material", "expected_output": "understanding", "query_count": 3, "session_topic_count": 1},
  {"id": 236, "title": "システム仕様の整理と改善提案（仕様書読み取り）", "session": "システム仕様の整理と改善提案", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 1},
  {"id": 237, "title": "TypeScript型定義からER図作成（社保等級マスタ）", "session": "TypeScript型定義からER図作成", "input_richness": "material", "expected_output": "artifact", "query_count": 5, "session_topic_count": 4},
  {"id": 238, "title": "UIテキスト改善：保険料入力指示", "session": "UIテキスト改善：保険料入力指示", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 23},
  {"id": 239, "title": "短時間労働者と短時間就労者の英語表記調査", "session": "UIテキスト改善：保険料入力指示", "input_richness": "contextualized", "expected_output": "fact", "query_count": 3, "session_topic_count": 23},
  {"id": 240, "title": "月途中での属性変更時の社保料計算ルール", "session": "UIテキスト改善：保険料入力指示", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 3, "session_topic_count": 23},
  {"id": 241, "title": "SQL WHERE句の件数上限とパフォーマンス", "session": "UIテキスト改善：保険料入力指示", "input_richness": "bare", "expected_output": "understanding", "query_count": 2, "session_topic_count": 23},
  {"id": 242, "title": "子ども・子育て支援金制度の正式英名", "session": "UIテキスト改善：保険料入力指示", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 23},
  {"id": 243, "title": "DB設計書の英語表記（effective/nominal upper limit）", "session": "UIテキスト改善：保険料入力指示", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 3, "session_topic_count": 23},
  {"id": 244, "title": "パンくずリストのドロップダウンUI設計", "session": "UIテキスト改善：保険料入力指示", "input_richness": "bare", "expected_output": "understanding", "query_count": 1, "session_topic_count": 23},
  {"id": 245, "title": "社保手続きの一括適用構成（エリア分割）", "session": "UIテキスト改善：保険料入力指示", "input_richness": "contextualized", "expected_output": "fact", "query_count": 3, "session_topic_count": 23},
  {"id": 246, "title": "労働保険の適用事業所の考え方", "session": "UIテキスト改善：保険料入力指示", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 23},
  {"id": 247, "title": "事業所一括構成のJSON/API設計", "session": "UIテキスト改善：保険料入力指示", "input_richness": "material", "expected_output": "understanding", "query_count": 5, "session_topic_count": 23},
  {"id": 248, "title": "健保と厚年の適用事業所の不一致ケース", "session": "UIテキスト改善：保険料入力指示", "input_richness": "contextualized", "expected_output": "fact", "query_count": 2, "session_topic_count": 23},
  {"id": 249, "title": "スプリットボタンのUIコンポーネント名称", "session": "UIテキスト改善：保険料入力指示", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 23},
  {"id": 250, "title": "Consumer/Master/Producerの役割分離", "session": "UIテキスト改善：保険料入力指示", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 23},
  {"id": 251, "title": "70-74歳の健保未加入・厚年加入の可能性", "session": "UIテキスト改善：保険料入力指示", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 23},
  {"id": 252, "title": "IT用語「移植」の英訳", "session": "UIテキスト改善：保険料入力指示", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 23},
  {"id": 253, "title": "フィルタ検索の属性選択上限のUXベストプラクティス", "session": "UIテキスト改善：保険料入力指示", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 23},
  {"id": 254, "title": "URLフラグメント（#パラメータ）の使い方", "session": "UIテキスト改善：保険料入力指示", "input_richness": "bare", "expected_output": "understanding", "query_count": 3, "session_topic_count": 23},
  {"id": 255, "title": "JSON構文チェックとスペルミス指摘", "session": "UIテキスト改善：保険料入力指示", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 23},
  {"id": 256, "title": "社保等級データの改善設計（operator/threshold方式）", "session": "UIテキスト改善：保険料入力指示", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 23},
  {"id": 257, "title": "表計算のデータ構造（疎行列・共有文字列）", "session": "UIテキスト改善：保険料入力指示", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 23},
  {"id": 258, "title": "APIスコープの意味と構造", "session": "UIテキスト改善：保険料入力指示", "input_richness": "material", "expected_output": "understanding", "query_count": 2, "session_topic_count": 23},
  {"id": 259, "title": "ブログ記事のアイキャッチ画像生成", "session": "UIテキスト改善：保険料入力指示", "input_richness": "material", "expected_output": "artifact", "query_count": 2, "session_topic_count": 23},
  {"id": 260, "title": "写真の色味補正（パキッとした明るい写真に）", "session": "ぱきっとした明るい写真になるように色味を修正して", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 261, "title": "Notion見出しインデントのStylus CSS", "session": "Notion 見出しインデント Stylus CSS", "input_richness": "bare", "expected_output": "artifact", "query_count": 2, "session_topic_count": 1},
  {"id": 262, "title": "「読んでください」の敬語表現", "session": "「読んでください」の敬語表現", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 2},
  {"id": 263, "title": "事業所と保険情報のAPI設計（OpenAPI Spec）", "session": "API 設計：事業所と保険情報", "input_richness": "material", "expected_output": "artifact", "query_count": 7, "session_topic_count": 6},
  {"id": 264, "title": "RoR ActiveRecord::Bitemporalの仕様調査", "session": "API 設計：事業所と保険情報", "input_richness": "bare", "expected_output": "understanding", "query_count": 4, "session_topic_count": 6},
  {"id": 265, "title": "DB技術の解説（DDL最適化・RTO・Binlog）", "session": "API 設計：事業所と保険情報", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 6},
  {"id": 266, "title": "労働保険の保険料納付サイクル", "session": "API 設計：事業所と保険情報", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 6},
  {"id": 267, "title": "労働保険の継続事業の一括と適用事業の法的解釈", "session": "API 設計：事業所と保険情報", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 2, "session_topic_count": 6},
  {"id": 268, "title": "事業所整理記号・番号の発行元調査", "session": "API 設計：事業所と保険情報", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 6},
  {"id": 269, "title": "SIMPの基礎物理量とハドロフィリックダークマター", "session": "TypeScript型定義からER図作成", "input_richness": "bare", "expected_output": "understanding", "query_count": 5, "session_topic_count": 4},
  {"id": 270, "title": "JSによる2リスト共通値判定と範囲交差ロジック", "session": "TypeScript型定義からER図作成", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 5, "session_topic_count": 4},
  {"id": 271, "title": "健保等級間マッピングの擬似コードとTS実装", "session": "TypeScript型定義からER図作成", "input_richness": "material", "expected_output": "understanding", "query_count": 3, "session_topic_count": 4},
  {"id": 272, "title": "UUID生成", "session": "UIテキスト改善：保険料入力指示", "input_richness": "bare", "expected_output": "artifact", "query_count": 1, "session_topic_count": 23},
  {"id": 273, "title": "複数健保組合加入の可能性と現実", "session": "複数健保組合加入の可能性と現実", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 2},
  {"id": 274, "title": "事業所マスタと適用事業所マスタの命名・ER図設計", "session": "複数健保組合加入の可能性と現実", "input_richness": "material", "expected_output": "understanding", "query_count": 4, "session_topic_count": 2},
  {"id": 275, "title": "協会けんぽにおける事業所の役割", "session": "協会けんぽにおける事業所の役割", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 1},
  {"id": 276, "title": "協会けんぽにおける事業所の名称と労務SaaS評価", "session": "協会けんぽにおける事業所の名称", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 3, "session_topic_count": 1},
  {"id": 277, "title": "SaaS画面のHTML/CSS実装（事業所管理画面）", "session": "SaaS画面のHTML_CSS実装", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 1},
  {"id": 278, "title": "jinjer事業所マスタの構造調査とER図設計", "session": "jinjer 事業所マスタの概要", "input_richness": "material", "expected_output": "understanding", "query_count": 8, "session_topic_count": 7},
  {"id": 279, "title": "口座情報の不完全状態の英語表現", "session": "jinjer 事業所マスタの概要", "input_richness": "contextualized", "expected_output": "fact", "query_count": 1, "session_topic_count": 7},
  {"id": 280, "title": "形式的バリデーションと意味的バリデーションの違い", "session": "jinjer 事業所マスタの概要", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 7},
  {"id": 281, "title": "従業員の所属事業所変更通知書類のユースケース", "session": "jinjer 事業所マスタの概要", "input_richness": "bare", "expected_output": "understanding", "query_count": 1, "session_topic_count": 7},
  {"id": 282, "title": "最後の1件を削除できない仕様の一般性", "session": "jinjer 事業所マスタの概要", "input_richness": "bare", "expected_output": "understanding", "query_count": 1, "session_topic_count": 7},
  {"id": 283, "title": "開発チームへのタスク割り当ての英語表現", "session": "jinjer 事業所マスタの概要", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 7},
  {"id": 284, "title": "Slackスレッド要約（WF Application comparison）", "session": "jinjer 事業所マスタの概要", "input_richness": "material", "expected_output": "artifact", "query_count": 1, "session_topic_count": 7},
  {"id": 285, "title": "「読んでください」の敬語表現セッション内のDB設計相談", "session": "「読んでください」の敬語表現", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 5, "session_topic_count": 2},
  {"id": 286, "title": "カスタム項目の無効化挙動のUX設計（HR SaaS内）", "session": "HR Tech SaaS_ Paper Pusher to People Partner", "input_richness": "contextualized", "expected_output": "understanding", "query_count": 1, "session_topic_count": 6},
  {"id": 287, "title": "Googleドキュメントのプルダウン選択肢上限", "session": "Googleドキュメントのプルダウン選択肢上限", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 4},
  {"id": 288, "title": "MySQL TEXT/ENUM型の調査", "session": "Googleドキュメントのプルダウン選択肢上限", "input_richness": "bare", "expected_output": "fact", "query_count": 3, "session_topic_count": 4},
  {"id": 289, "title": "CSV仕様書の英語表現チェック", "session": "Googleドキュメントのプルダウン選択肢上限", "input_richness": "material", "expected_output": "artifact", "query_count": 2, "session_topic_count": 4},
  {"id": 290, "title": "Microsoft公式がExcelをカタカナ表記している箇所", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "fact", "query_count": 2, "session_topic_count": 20},
  {"id": 291, "title": "HTMLラジオボタンの作成", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "artifact", "query_count": 1, "session_topic_count": 20},
  {"id": 292, "title": "開発者ツールでの要素追加方法", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 20},
  {"id": 293, "title": "JSON形式のkey-value構造の一般性", "session": "Googleスプレッドシートで行番号を特定する", "input_richness": "bare", "expected_output": "understanding", "query_count": 1, "session_topic_count": 20},
  {"id": 294, "title": "バリデーションの種類（構文/セマンティック）（別セッション）", "session": "Mac ターミナル プロンプト表示問題", "input_richness": "bare", "expected_output": "fact", "query_count": 1, "session_topic_count": 4},
  {"id": 295, "title": "CSVエクスポートチェックボックスの英語ラベル提案", "session": "Mac ターミナル プロンプト表示問題", "input_richness": "contextualized", "expected_output": "artifact", "query_count": 1, "session_topic_count": 4}
];
